Repository siho-song/8to10, pull requests merged in 2024-08, with the labels that each got.

#106 #103[게시판 구현]/#105-검색조건-객체-구현
  src/main/java/show/schedulemanagement/dto/board/SearchCondition.java
  src/main/java/show/schedulemanagement/dto/board/SortCondition.java
Labels: enhancement

#107 #39[일정 컨트롤러 및 서비스 개발]/#98-메서드명-변경
  src/main/java/show/schedulemanagement/service/schedule/FScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/NScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/ScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/ScheduleServiceImpl.java
Labels: Refactor

#109 #100[일반일정 Detail 삭제]/#108-테스트코드-수정
  src/test/java/show/schedulemanagement/TestConfig.java
  src/test/java/show/schedulemanagement/service/schedule/ScheduleDetailServiceImplTest.java
Labels: enhancement

#111 #103[게시판 구현]/#110-게시글-도메인-수정
  src/main/java/show/schedulemanagement/domain/board/Board.java
Labels: enhancement

#123 #54[고정 일정 폼 변경]/#120-로고이미지-추가
  src/main/resources/static/favicons/favicon-16x16.png
  src/main/resources/static/favicons/favicon-32x32.png
  src/main/resources/static/favicons/favicon-96x96.png
  src/main/resources/static/images/logo.png
  src/main/resources/templates/community/board.html
  src/main/resources/templates/community/post/createPost.html
  src/main/resources/templates/community/post/viewPost.html
  src/main/resources/templates/home/achievements.html
  src/main/resources/templates/home/fullcalendar.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/mypage/board-related/my-comments.html
  src/main/resources/templates/mypage/board-related/my-posts.html
  src/main/resources/templates/mypage/board-related/my-scraps.html
  src/main/resources/templates/mypage/change-pages/change-email.html
  src/main/resources/templates/mypage/change-pages/change-nickname.html
  src/main/resources/templates/mypage/change-pages/change-password.html
  src/main/resources/templates/mypage/change-pages/change-phone.html
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/signup/complete.html
  src/main/resources/templates/signup/signup.html
Labels: enhancement, Refactor

#124 #103[게시판 구현]/#110-변수타입-변경
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
Labels: enhancement

#126 #103[게시판 구현]/#112-게시판-서비스-구현
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
Labels: enhancement

#135 #85[개발 환경 수정]/코드 리팩토링
  src/main/java/show/schedulemanagement/controller/schedule/FScheduleController.java
  src/main/java/show/schedulemanagement/controller/schedule/NScheduleController.java
  src/main/java/show/schedulemanagement/controller/schedule/ScheduleController.java
  src/main/java/show/schedulemanagement/domain/achievement/CatUnitAch.java
  src/main/java/show/schedulemanagement/domain/schedule/ScheduleDay.java
  src/main/java/show/schedulemanagement/dto/Result.java
  src/main/java/show/schedulemanagement/security/filter/CustomAuthenticationFilter.java
  src/main/java/show/schedulemanagement/service/schedule/FScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/NScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/ScheduleService.java
  src/main/java/show/schedulemanagement/service/schedule/ScheduleServiceImpl.java
  src/main/resources/data-dev.sql
Labels: Refactor

#134 #54[고정 일정 폼 변경]/#121-주간캘린더-시간대-변경
  src/main/resources/static/js/home/fullcalendarInit.js
Labels: enhancement, Refactor

#136 #103[게시판 구현]/#113-게시글-조회
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/repository/board/BoardRepositoryCustomImplTest.java
Labels: enhancement

#138 #103[게시판 구현]/#114-게시글-삭제
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/repository/board/BoardHeartsRepository.java
  src/main/java/show/schedulemanagement/repository/board/BoardScrapRepository.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyHeartsRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
Labels: enhancement

#139 #85[개발 환경 수정]/BoardAttachment 삭제
  src/main/java/show/schedulemanagement/domain/board/BoardAttachment.java
  src/main/resources/data-dev.sql
  src/test/resources/data-test.sql
Labels: enhancement

#140 #103[게시판 구현]/#113-게시글-조회
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  src/main/java/show/schedulemanagement/dto/board/BoardPageRequest.java
  src/main/java/show/schedulemanagement/dto/board/BoardPageResponse.java
  src/main/java/show/schedulemanagement/dto/board/BoardSaveRequest.java
  src/main/java/show/schedulemanagement/dto/board/BoardSaveResponse.java
  src/main/java/show/schedulemanagement/dto/board/BoardSearchResponse.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplyResponseDto.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepositoryCustom.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepositoryCustomImpl.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/repository/board/BoardRepositoryCustomImplTest.java
  src/test/resources/data-test.sql
Labels: enhancement

#141 #103[게시판 구현]/#115-게시글-수정
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/dto/board/BoardUpdateRequest.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/repository/board/BoardRepositoryCustomImplTest.java
Labels: enhancement

#143 #103[게시판 구현]/#116-댓글-삽입
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  src/main/java/show/schedulemanagement/dto/board/BoardSearchResponse.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplySaveRequest.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplySaveResponse.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplySearchResponse.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyRepository.java
  src/main/java/show/schedulemanagement/service/board/ReplyService.java
  src/main/java/show/schedulemanagement/service/board/ReplyServiceImpl.java
  src/main/resources/data-dev.sql
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/resources/data-test.sql
Labels: enhancement

#145 #103[게시판 구현]/#117-댓글-조회
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyRepository.java
  src/main/java/show/schedulemanagement/service/board/ReplyService.java
  src/main/java/show/schedulemanagement/service/board/ReplyServiceImpl.java
  src/test/java/show/schedulemanagement/service/board/ReplyServiceImplTest.java
Labels: enhancement

#146 #103[게시판 구현]/#118-댓글-삭제
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyRepository.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartsService.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartsServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/ReplyService.java
  src/main/java/show/schedulemanagement/service/board/ReplyServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyServiceImplTest.java
  src/test/resources/data-test.sql
Labels: enhancement

#147 #103[게시판 구현]/#119-댓글-수정
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplyUpdateRequest.java
  src/main/java/show/schedulemanagement/service/board/ReplyService.java
  src/main/java/show/schedulemanagement/service/board/ReplyServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyServiceImplTest.java
Labels: enhancement

#156 #103[게시판 구현]/#155-게시글-단건조회-방식-변경
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/BoardHeart.java
  src/main/java/show/schedulemanagement/domain/board/reply/ReplyHeart.java
  src/main/java/show/schedulemanagement/dto/board/BoardSearchResponse.java
  src/main/java/show/schedulemanagement/repository/board/BoardHeartRepository.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepositoryCustom.java
  src/main/java/show/schedulemanagement/repository/board/BoardRepositoryCustomImpl.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyHeartRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardService.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartService.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/ReplyServiceImpl.java
  src/main/resources/data-dev.sql
  src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
  src/test/resources/data-test.sql
Labels: enhancement

#158 #103[게시판 구현]/엔드포인트-변경
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
Labels: enhancement

#160 #103[게시판 구현]/#149-게시글-좋아요-삭제
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/dto/board/BoardSearchResponse.java
  src/main/java/show/schedulemanagement/repository/board/BoardHeartRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardHeartService.java
  src/main/java/show/schedulemanagement/service/board/BoardHeartServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardHeartServiceTest.java
Labels: enhancement

#163 #103[게시판 구현]/#150-댓글-좋아요-추가
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  src/main/java/show/schedulemanagement/domain/board/reply/ReplyHeart.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyHeartRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardHeartService.java
  src/main/java/show/schedulemanagement/service/board/BoardHeartServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartService.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardHeartServiceTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyHeartServiceTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyServiceTest.java
Labels: enhancement

#164 #103[게시판 구현]/#151-댓글-좋아요-삭제
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  src/main/java/show/schedulemanagement/dto/board/reply/ReplySearchResponse.java
  src/main/java/show/schedulemanagement/repository/board/reply/ReplyHeartRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartService.java
  src/main/java/show/schedulemanagement/service/board/ReplyHeartServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardHeartServiceTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyHeartServiceTest.java
  src/test/resources/data-test.sql
Labels: enhancement

#165 #103[게시판 구현]/HttpMethod-변경
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
Labels: enhancement

#166 #103[게시판 구현]/#153-스크랩-추가
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/domain/board/BoardScrap.java
  src/main/java/show/schedulemanagement/repository/board/BoardScrapRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardScrapService.java
  src/main/java/show/schedulemanagement/service/board/BoardScrapServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardScrapServiceTest.java
Labels: enhancement

#167 #103[게시판 구현]/#152-스크랩-삭제
  src/main/java/show/schedulemanagement/controller/board/BoardController.java
  src/main/java/show/schedulemanagement/domain/board/Board.java
  src/main/java/show/schedulemanagement/repository/board/BoardScrapRepository.java
  src/main/java/show/schedulemanagement/service/board/BoardScrapService.java
  src/main/java/show/schedulemanagement/service/board/BoardScrapServiceImpl.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/service/board/BoardScrapServiceTest.java
Labels: enhancement

#172 #64[커뮤니티-뷰-개발]/#169-게시글-페이지-검색뷰로-전 환
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/viewChanger.js
  src/main/resources/templates/community/board.html
  src/main/resources/templates/home/fullcalendar.html
Labels: enhancement
