Repository siho-song/8to10, pull requests merged in 2024-11, with the labels that each got.

#243 #241[Refresh토큰 발급]/#242-Auth 테이블 추가
  src/main/java/show/schedulemanagement/controller/LoginController.java
  src/main/java/show/schedulemanagement/domain/auth/Auth.java
  src/main/java/show/schedulemanagement/domain/member/Member.java
  src/main/java/show/schedulemanagement/domain/member/Role.java
  src/main/java/show/schedulemanagement/dto/auth/MemberDetailsDto.java
  src/main/java/show/schedulemanagement/service/MemberService.java
  src/main/java/show/schedulemanagement/service/MemberServiceImpl.java
  src/main/java/show/schedulemanagement/service/auth/MemberDetailsService.java
  src/main/java/show/schedulemanagement/service/signup/SignUpServiceImpl.java
  src/main/resources/data-dev.sql
  src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/ScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/ScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/vschedule/VScheduleServiceTest.java
  src/test/resources/data-test.sql
Labels: enhancement, Refactor

#245 #241[RefreshToken 발급]/#244-RefreshToken 생성 및 엔드포인트 구현
  src/main/java/show/schedulemanagement/config/auth/SecurityConfig.java
  src/main/java/show/schedulemanagement/config/web/MemberArgumentResolver.java
  src/main/java/show/schedulemanagement/controller/AuthController.java
  src/main/java/show/schedulemanagement/controller/HomeController.java
  src/main/java/show/schedulemanagement/controller/LoginController.java
  src/main/java/show/schedulemanagement/domain/auditing/AuditorAwareImpl.java
  src/main/java/show/schedulemanagement/domain/auth/Auth.java
  src/main/java/show/schedulemanagement/domain/auth/MemberDetails.java
  src/main/java/show/schedulemanagement/dto/auth/AccessTokenResponse.java
  src/main/java/show/schedulemanagement/filter/JwtAuthorizationFilter.java
  src/main/java/show/schedulemanagement/handler/AuthSuccessHandler.java
  src/main/java/show/schedulemanagement/provider/CustomAuthenticationProvider.java
  src/main/java/show/schedulemanagement/provider/TokenProvider.java
  src/main/java/show/schedulemanagement/repository/auth/AuthRepository.java
  src/main/java/show/schedulemanagement/service/MemberServiceImpl.java
  src/main/java/show/schedulemanagement/service/auth/AuthService.java
  src/main/java/show/schedulemanagement/service/auth/MemberDetailsService.java
  src/main/java/show/schedulemanagement/utils/BearerAuthorizationUtils.java
  src/main/java/show/schedulemanagement/utils/TokenProvider.java
  src/main/resources/data-dev.sql
  src/test/java/show/schedulemanagement/controller/AuthControllerTest.java
  src/test/java/show/schedulemanagement/controller/LoginControllerTest.java
  src/test/java/show/schedulemanagement/controller/achievement/AchievementControllerTest.java
  src/test/java/show/schedulemanagement/controller/board/BoardControllerTest.java
  src/test/java/show/schedulemanagement/controller/board/reply/ReplyControllerTest.java
  src/test/java/show/schedulemanagement/controller/schedule/FScheduleControllerTest.java
  src/test/java/show/schedulemanagement/controller/schedule/NScheduleControllerTest.java
  src/test/java/show/schedulemanagement/controller/schedule/ScheduleControllerTest.java
  src/test/java/show/schedulemanagement/controller/schedule/VScheduleControllerTest.java
  src/test/java/show/schedulemanagement/service/auth/AuthServiceTest.java
  src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
  src/test/java/show/schedulemanagement/service/board/ReplyHeartServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/ScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/ScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleDetailServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleServiceTest.java
  src/test/java/show/schedulemanagement/service/schedule/vschedule/VScheduleServiceTest.java
  src/test/resources/data-test.sql
Labels: enhancement, style, Refactor

#252 #246[백엔드, 프론트엔드 코드 분리]/#251-백엔드-디렉터리-정적리소스-삭제
  8to10_backend/src/main/resources/static/css/styles.css
  8to10_backend/src/main/resources/static/favicons/favicon-16x16.png
  8to10_backend/src/main/resources/static/favicons/favicon-32x32.png
  8to10_backend/src/main/resources/static/favicons/favicon-96x96.png
  8to10_backend/src/main/resources/static/images/community.png
  8to10_backend/src/main/resources/static/images/home.png
  8to10_backend/src/main/resources/static/images/logo.png
  8to10_backend/src/main/resources/static/images/mypage.png
  8to10_backend/src/main/resources/static/images/running.gif
  8to10_backend/src/main/resources/static/index.html
  8to10_backend/src/main/resources/static/js/community/board.js
  8to10_backend/src/main/resources/static/js/community/createPost.js
  8to10_backend/src/main/resources/static/js/community/viewPost.js
  8to10_backend/src/main/resources/static/js/home/achievements.js
  8to10_backend/src/main/resources/static/js/home/form/addScheduleForm.js
  8to10_backend/src/main/resources/static/js/home/form/scheduleCategoryForm.js
  8to10_backend/src/main/resources/static/js/home/form/scheduleDetailForm.js
  8to10_backend/src/main/resources/static/js/home/form/validation/validateFixedScheduleForm.js
  8to10_backend/src/main/resources/static/js/home/form/validation/validateScheduleForm.js
  8to10_backend/src/main/resources/static/js/home/fullcalendarInit.js
  8to10_backend/src/main/resources/static/js/home/toggle.js
  8to10_backend/src/main/resources/static/js/home/utils/date-option.js
  8to10_backend/src/main/resources/static/js/home/utils/time-option.js
  8to10_backend/src/main/resources/static/js/mypage/myComments.js
  8to10_backend/src/main/resources/static/js/mypage/myPosts.js
  8to10_backend/src/main/resources/static/js/mypage/myScraps.js
  8to10_backend/src/main/resources/static/js/signUp/signUp.js
  8to10_backend/src/main/resources/static/js/signUp/validateSignUp.js
  8to10_backend/src/main/resources/static/js/viewChanger.js
  8to10_backend/src/main/resources/templates/home/achievements.html
  8to10_backend/src/main/resources/templates/home/fullcalendar.html
  8to10_backend/src/main/resources/templates/login/login.html
  8to10_backend/src/main/resources/templates/mypage/board-related/my-comments.html
  8to10_backend/src/main/resources/templates/mypage/board-related/my-posts.html
  8to10_backend/src/main/resources/templates/mypage/board-related/my-scraps.html
  8to10_backend/src/main/resources/templates/mypage/change-pages/change-email.html
  8to10_backend/src/main/resources/templates/mypage/change-pages/change-nickname.html
  8to10_backend/src/main/resources/templates/mypage/change-pages/change-password.html
  8to10_backend/src/main/resources/templates/mypage/change-pages/change-phone.html
  8to10_backend/src/main/resources/templates/mypage/mypage.html
  8to10_backend/src/main/resources/templates/signup/complete.html
  8to10_backend/src/main/resources/templates/signup/signup.html
  8to10_frontend/.gitignore
Labels: enhancement

#260 #255[Access Token, Refresh Token 사용으로 인한 요청 메소드 변경]/#256-Access-Token-로컬-스토리지-저장-후-API-요청에-적용
  8to10_frontend/src/components/community/board/Board.jsx
  8to10_frontend/src/components/community/post/CreateOrEditPost.jsx
  8to10_frontend/src/components/community/post/PostContent.jsx
  8to10_frontend/src/components/community/post/PostDetail.jsx
  8to10_frontend/src/components/community/post/reply/CommentDetail.jsx
  8to10_frontend/src/components/community/post/reply/CreateComment.jsx
  8to10_frontend/src/components/community/post/reply/ReplyDetail.jsx
  8to10_frontend/src/components/context/AuthContext.jsx
  8to10_frontend/src/components/context/AuthProvider.jsx
  8to10_frontend/src/components/context/FullCalendarContext.jsx
  8to10_frontend/src/components/home/HomeLeftSideBar.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/FixedScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/NormalScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/login/Login.jsx
Labels: enhancement

#263 #255[Access Token, Refresh Token 사용으로 인한 요청 메소드 변경]/#257-Access-Token-만료에-대한-refreshAccessToken-메소드-구현
  8to10_frontend/src/components/context/AuthProvider.jsx
  8to10_frontend/src/components/home/MainView.jsx
  8to10_frontend/src/constants/HttpMethods.js
  8to10_frontend/src/constants/HttpStatusCodes.js
  8to10_frontend/src/utils/TokenUtils.js
Labels: enhancement

#264 #255[Access Token, Refresh Token 사용으로 인한 요청 메소드 변경]/#261-Access-Token을-통한-인증-상태-재설정-구현
  8to10_frontend/src/components/PrivateRoute.jsx
Labels: enhancement

#265 #234[Security 인증 필터 커스텀 예외 구현]
  8to10_backend/src/main/java/show/schedulemanagement/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/AuthException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/BadRequestException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/BusinessException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/DuplicatedException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/ExceptionCode.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/InvalidLevelException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/InvalidScheduleCreationException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/InvalidTokenException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/MismatchException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/NotFoundEntityException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/UserAuthenticationException.java
  8to10_backend/src/main/java/show/schedulemanagement/filter/EmailPasswordAuthenticationFilter.java
  8to10_backend/src/main/java/show/schedulemanagement/filter/JwtAuthorizationFilter.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/AuthFailureHandler.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/AuthFilterExceptionHandler.java
  8to10_backend/src/main/java/show/schedulemanagement/provider/CustomAuthenticationProvider.java
  8to10_backend/src/main/java/show/schedulemanagement/service/auth/MemberDetailsService.java
Labels: enhancement

#268 #266[ControllerAdvice 구현 및 커스텀 예외 적용]/#267-로직-구현
  8to10_backend/src/main/java/show/schedulemanagement/controller/AuthController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/SignUpController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/Schedule.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/ErrorResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/schedule/request/nschedule/NScheduleDetailUpdate.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/GlobalControllerAdvice.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MemberServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/auth/AuthService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardHeartServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardScrapServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/reply/ReplyHeartServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/reply/ReplyServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/ScheduleDetailService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/ScheduleService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/ScheduleServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/fschedule/FScheduleDetailService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/fschedule/FScheduleService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/nschedule/NScheduleDetailService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/nschedule/NScheduleService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/timeslot/TimeSlotService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/vschedule/VScheduleService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/signup/SignUpService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/signup/SignUpServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/signup/SignUpValidationService.java
  8to10_backend/src/main/java/show/schedulemanagement/utils/BearerAuthorizationUtils.java
  8to10_backend/src/main/java/show/schedulemanagement/validator/schedule/objecterror/StartDateBeforeEqEndDateValidator.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/AuthControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/repository/schedule/ScheduleRepositoryCustomImplTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/ReplyServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/ScheduleDetailServiceTest.java
Labels: enhancement

#271 #266[ControllerAdvice 구현 및 커스텀 예외 적용]/테스트 로직 변경
  8to10_backend/src/main/java/show/schedulemanagement/service/signup/SignUpService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/AuthControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/SignUpControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/auth/AuthServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardHeartServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardScrapServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/ReplyHeartServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/ReplyServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleDetailServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleDetailServiceTest.java
Labels: enhancement

#273 #272[유저 스탯 카드 조회 기능 구현]
  8to10_backend/src/main/java/show/schedulemanagement/controller/HomeController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/member/Role.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/UserStatsResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/achievement/AchievementRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/HomeService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/achievement/AchievementService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/HomeControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/HomeServiceTest.java
Labels: enhancement

#275 #229[마이페이지 개발]/#274-프로필 불러오기
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/ProfileResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#283 #229[마이페이지 개발]/#276-내가 쓴 게시글 보기
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/MemberBoardsResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/board/BoardRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardServiceImpl.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#285 #229[마이페이지 개발]/#280-내가 스크랩한 게시글 보기
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/ScrappedBoardResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/board/BoardScrapRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardScrapService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardScrapServiceImpl.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#286 #229[마이페이지 개발]/#279-닉네임 수정
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/member/Member.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/NicknameUpdateRequest.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MemberService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MemberServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#287 #229[마이페이지 개발]/#278-비밀번호 수정
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/member/Member.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/MemberBoardsResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/MemberRepliesResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/PasswordUpdateRequest.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/mypage/ProfileResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/main/java/show/schedulemanagement/validator/signup/fielderror/PasswordValidator.java
  8to10_backend/src/main/resources/ValidationMessages.properties
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/HomeServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#288 #229[마이페이지 개발]/#281-프로필사진 등록,수정
  8to10_backend/.gitignore
  8to10_backend/src/main/java/show/schedulemanagement/constant/AppConstant.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/member/Member.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/ExceptionCode.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MultipartFileStorageService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
Labels: enhancement

#291 #255[Access Token, Refresh Token 사용으로 인한 요청 메소드 변경]/#259-Access-Token-만료-시-재발급-후-재요청-메소드-구현-및-적용
  8to10_frontend/package-lock.json
  8to10_frontend/package.json
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthApi.js
  8to10_frontend/src/api/CustomErrors.js
  8to10_frontend/src/api/api.js
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/community/board/Board.jsx
  8to10_frontend/src/components/community/post/CreateOrEditPost.jsx
  8to10_frontend/src/components/community/post/PostContent.jsx
  8to10_frontend/src/components/community/post/PostDetail.jsx
  8to10_frontend/src/components/community/post/reply/CommentDetail.jsx
  8to10_frontend/src/components/community/post/reply/CreateComment.jsx
  8to10_frontend/src/components/community/post/reply/ReplyDetail.jsx
  8to10_frontend/src/components/context/AuthProvider.jsx
  8to10_frontend/src/components/home/FullcalendarInit.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/FixedScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/NormalScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleTimeUtils/TimeUtils.jsx
  8to10_frontend/src/components/login/Login.jsx
  8to10_frontend/src/context/AuthContext.jsx
  8to10_frontend/src/context/AuthProvider.jsx
  8to10_frontend/src/context/FullCalendarContext.jsx
  8to10_frontend/src/context/UseAuth.jsx
Labels: enhancement

#293 #255[Access Token, Refresh Token 사용으로 인한 요청 메소드 변경]/#292-이전-PR-후속조치-컴포넌트명-수정-및-요청-인터셉터-수정
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthApi.js
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/components/PrivateHeader.jsx
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/PublicHeader.jsx
  8to10_frontend/src/components/community/board/Board.jsx
  8to10_frontend/src/components/community/board/BoardView.jsx
  8to10_frontend/src/components/community/post/CreateOrEditPost.jsx
  8to10_frontend/src/components/community/post/PostDetailView.jsx
  8to10_frontend/src/components/community/post/PostItem.jsx
  8to10_frontend/src/components/community/post/PostView.jsx
  8to10_frontend/src/components/community/post/reply/CommentItem.jsx
  8to10_frontend/src/components/community/post/reply/CommentSection.jsx
  8to10_frontend/src/components/community/post/reply/CreateComment.jsx
  8to10_frontend/src/components/community/post/reply/ReplyItem.jsx
  8to10_frontend/src/components/home/FullcalendarView.jsx
  8to10_frontend/src/components/home/MainView.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/FixedScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/NormalScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/login/Login.jsx
  8to10_frontend/src/components/signUp/SignUp.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/constants/RequestHeaderConfig.js
  8to10_frontend/src/context/FullCalendarContext.jsx
  8to10_frontend/src/helpers/AxiosUtils.js
  8to10_frontend/src/helpers/TimeUtils.js
  8to10_frontend/src/helpers/TokenUtils.js
  8to10_frontend/src/pages/BoardPost.jsx
  8to10_frontend/src/pages/Community.jsx
  8to10_frontend/src/pages/Home.jsx
  8to10_frontend/src/pages/MyPage.jsx
  8to10_frontend/src/pages/Post.jsx
  8to10_frontend/src/utils/TokenUtils.js
Labels: enhancement

#299 #294[유저 스탯카드 컴포넌트 구현]
  8to10_frontend/src/components/home/HomeLeftSideBar.jsx
  8to10_frontend/src/components/home/userStatsCard/UserStatsCard.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
Labels: enhancement

#301 #290[SSE 연결 구현]/#300-SSE 연결 구현
  8to10_backend/src/main/java/show/schedulemanagement/config/RedisConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/config/auth/JwtProperties.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/NotificationController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/SignUpController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/achievement/AchievementController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/board/reply/ReplyController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/schedule/NScheduleController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/schedule/ScheduleController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/notification/Notification.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/notification/NotificationType.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/AuthException.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/ExceptionCode.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/SseSendException.java
  8to10_backend/src/main/java/show/schedulemanagement/filter/EmailPasswordAuthenticationFilter.java
  8to10_backend/src/main/java/show/schedulemanagement/filter/JwtAuthorizationFilter.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/AuthFailureHandler.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/AuthFilterExceptionHandler.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/GlobalControllerAdvice.java
  8to10_backend/src/main/java/show/schedulemanagement/provider/CustomAuthenticationProvider.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/notification/SseEmitterRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/MyPageService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/auth/MemberDetailsService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/member/MemberService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/member/MemberServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/SseEmitterService.java
  8to10_backend/src/main/resources/data-dev.sql
  8to10_backend/src/test/java/show/schedulemanagement/controller/AuthControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/NotificationControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/repository/schedule/ScheduleRepositoryCustomImplTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/HomeServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/MyPageServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/achievement/AchievementServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardHeartServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardScrapServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/ReplyHeartServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/ReplyServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/ScheduleServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleDetailServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/fschedule/FScheduleServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleDetailServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/nschedule/NScheduleServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/schedule/vschedule/VScheduleServiceTest.java
  8to10_backend/src/test/resources/data-test.sql
Labels: enhancement

#303 #290[알람 기능 개발]/#302-댓글 알람기능 개발
  8to10_backend/build.gradle
  8to10_backend/src/main/java/show/schedulemanagement/config/global/AsyncConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/config/global/CustomPhysicalNamingStrategy.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/board/reply/Reply.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/NotificationResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/InvalidRedisMessageException.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/notification/NotificationRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/reply/ReplyServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/event/NotificationEvent.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/AsyncEventPublisher.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationMessage.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationService.java
Labels: enhancement

#306 #290[알람 기능 개발]/#305-성취도 알람 기능 구현
  8to10_backend/src/main/java/show/schedulemanagement/SchedulemanagementApplication.java
  8to10_backend/src/main/java/show/schedulemanagement/config/RedisConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/notification/NotificationType.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/GlobalControllerAdvice.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/RedisChannelEventListener.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/achievement/AchievementRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/notification/NotificationRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/achievement/AchievementService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/AsyncEventPublisher.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/FeedbackMessage.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationMessage.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/SseEmitterService.java
Labels: enhancement

#308 #290[알람 기능 개발]/#307-todo 리스트 업데이트 마감 알람 기능 구현
  8to10_backend/src/main/java/show/schedulemanagement/service/member/MemberService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/member/MemberServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/AsyncEventPublisher.java
Labels: enhancement

#310 #290[알림 기능 개발]/#309-알림 삭제
  8to10_backend/src/main/java/show/schedulemanagement/controller/NotificationController.java
  8to10_backend/src/main/java/show/schedulemanagement/exception/ExceptionCode.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/notification/NotificationRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/NotificationControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/notification/NotificationServiceTest.java
Labels: enhancement

#312 #290[알림 기능 개발]/#311-알림 읽음 처리
  8to10_backend/src/main/java/show/schedulemanagement/controller/NotificationController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/notification/Notification.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationService.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/NotificationControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/notification/NotificationServiceTest.java
Labels: enhancement

#313 #295[투두리스트 구현]
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/community/post/PostItem.jsx
  8to10_frontend/src/components/community/post/PostView.jsx
  8to10_frontend/src/components/community/post/reply/CommentItem.jsx
  8to10_frontend/src/components/community/post/reply/ReplyItem.jsx
  8to10_frontend/src/components/home/FullcalendarView.jsx
  8to10_frontend/src/components/home/HomeLeftSideBar.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/FixedScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/NormalScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/home/todoList/TodoItem.jsx
  8to10_frontend/src/components/home/todoList/TodoItemsList.jsx
  8to10_frontend/src/components/home/todoList/TodoList.jsx
  8to10_frontend/src/components/home/todoList/TodoListHeader.jsx
  8to10_frontend/src/components/login/Login.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/context/FullCalendarContext.jsx
  8to10_frontend/src/context/auth/AuthContext.jsx
  8to10_frontend/src/context/auth/AuthProvider.jsx
  8to10_frontend/src/context/auth/UseAuth.jsx
  8to10_frontend/src/context/fullCalendar/FullCalendarContext.jsx
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/context/fullCalendar/useCalendar.jsx
  8to10_frontend/src/helpers/AxiosConfig.js
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/helpers/TimeFormatter.js
  8to10_frontend/src/helpers/TokenManager.js
  8to10_frontend/src/styles/home/LeftSideBar..css
  8to10_frontend/src/styles/home/TodoList.css
Labels: enhancement

#315 #314[코드 리팩토링]
  8to10_backend/Dockerfile
  8to10_backend/build.gradle
  8to10_backend/src/main/java/show/schedulemanagement/SchedulemanagementApplication.java
  8to10_backend/src/main/java/show/schedulemanagement/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/config/global/AsyncConfig.java
  8to10_backend/src/main/java/show/schedulemanagement/config/web/MemberArgumentResolver.java
  8to10_backend/src/main/java/show/schedulemanagement/constant/AppConstantValidator.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/AuthController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/MyPageController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/SignUpController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/schedule/NScheduleController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/schedule/ScheduleController.java
  8to10_backend/src/main/java/show/schedulemanagement/controller/schedule/VScheduleController.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/auditing/AuditorAwareImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/auditing/baseentity/BaseEntity.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/auth/Auth.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/board/Board.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/member/Member.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/notification/Notification.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/Schedule.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/fschedule/FScheduleDetail.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/nschedule/NSchedule.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/nschedule/NScheduleDetail.java
  8to10_backend/src/main/java/show/schedulemanagement/domain/schedule/vschedule/VSchedule.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/Result.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/UserStatsResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/schedule/request/ScheduleSave.java
  8to10_backend/src/main/java/show/schedulemanagement/dto/schedule/response/nschedule/NScheduleUpdateResponse.java
  8to10_backend/src/main/java/show/schedulemanagement/handler/AuthSuccessHandler.java
  8to10_backend/src/main/java/show/schedulemanagement/provider/TokenProvider.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/board/BoardRepositoryCustom.java
  8to10_backend/src/main/java/show/schedulemanagement/repository/board/BoardScrapRepository.java
  8to10_backend/src/main/java/show/schedulemanagement/service/HomeService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/achievement/AchievementService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardScrapService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/BoardService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/reply/ReplyHeartService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/board/reply/ReplyServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/event/reply/ReplyEvent.java
  8to10_backend/src/main/java/show/schedulemanagement/service/event/reply/ReplyHeartAddEvent.java
  8to10_backend/src/main/java/show/schedulemanagement/service/event/reply/ReplyHeartSubEvent.java
  8to10_backend/src/main/java/show/schedulemanagement/service/member/MemberServiceImpl.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/FeedbackMessage.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/NotificationService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/notification/SseEmitterService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/schedule/vschedule/VScheduleService.java
  8to10_backend/src/main/java/show/schedulemanagement/service/signup/SignUpService.java
  8to10_backend/src/main/java/show/schedulemanagement/validator/schedule/objecterror/StartBeforeEndValidator.java
  8to10_backend/src/main/java/show/schedulemanagement/validator/schedule/objecterror/StartDateBeforeEqEndDateValidator.java
  8to10_backend/src/main/java/show/schedulemanagement/validator/signup/fielderror/UsernameValidator.java
  8to10_backend/src/main/resources/data-dev.sql
  8to10_backend/src/test/java/show/schedulemanagement/controller/AuthControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/HomeControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/MyPageControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/NotificationControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/controller/SignUpControllerTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/HomeServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/auth/AuthServiceTest.java
  8to10_backend/src/test/java/show/schedulemanagement/service/board/BoardServiceTest.java
Labels: enhancement, Refactor

#318 #314[코드 리팩토링]/3
  8to10_backend/src/main/java/com/eighttoten/service/HomeService.java
  8to10_backend/src/main/java/com/eighttoten/service/MultipartFileStorageService.java
  8to10_backend/src/main/java/com/eighttoten/service/MyPageService.java
  8to10_backend/src/main/java/com/eighttoten/service/member/MemberService.java
  8to10_backend/src/main/java/com/eighttoten/service/member/MemberServiceImpl.java
  8to10_backend/src/main/java/com/eighttoten/service/notification/AsyncEventPublisher.java
  8to10_backend/src/main/java/com/eighttoten/service/notification/FeedbackMessage.java
  8to10_backend/src/main/java/com/eighttoten/service/notification/NotificationMessage.java
  8to10_backend/src/main/java/com/eighttoten/service/notification/NotificationService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/ScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/ScheduleServiceImpl.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/fschedule/FScheduleDetailService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/fschedule/FScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/nschedule/NScheduleDetailService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/nschedule/NScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/timeslot/TimeSlot.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/timeslot/TimeSlotService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/vschedule/VScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/service/signup/SignUpService.java
Labels: style, Refactor

#319 #314[코드 리팩토링]/4
  8to10_backend/src/test/resources/data-test.sql
Labels: enhancement

#321 #304[알림 기능 구현]
  8to10_frontend/package-lock.json
  8to10_frontend/package.json
  8to10_frontend/src/components/PrivateHeader.jsx
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/community/post/CreateOrEditPost.jsx
  8to10_frontend/src/components/community/post/PostView.jsx
  8to10_frontend/src/components/community/post/reply/CommentItem.jsx
  8to10_frontend/src/components/community/post/reply/ReplyItem.jsx
  8to10_frontend/src/components/notification/Notification.jsx
  8to10_frontend/src/components/notification/NotificationItem.jsx
  8to10_frontend/src/components/notification/NotificationPopup.jsx
  8to10_frontend/src/constants/NotificationTypes.js
  8to10_frontend/src/pages/BoardPost.jsx
  8to10_frontend/src/pages/Community.jsx
  8to10_frontend/src/pages/Home.jsx
  8to10_frontend/src/pages/MyPage.jsx
  8to10_frontend/src/pages/Post.jsx
  8to10_frontend/src/styles/community/Board.css
  8to10_frontend/src/styles/notification/Notification.css
Labels: enhancement

#322 #290[알림 기능 개발]/알림 아이디도 포함해서 응답
  8to10_backend/src/main/java/com/eighttoten/domain/notification/NotificationType.java
  8to10_backend/src/main/java/com/eighttoten/dto/NotificationResponse.java
Labels: enhancement
