Repository siho-song/8to10, pull requests merged in 2024-12, with the labels that each got.

#324 #323[Auth 테이블 제거 및 레프레시 토큰 레디스 사용]
  8to10_backend/build.gradle
  8to10_backend/src/main/java/com/eighttoten/EightToTenApplication.java
  8to10_backend/src/main/java/com/eighttoten/aspect/ExecutionTimeAspect.java
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/com/eighttoten/domain/auth/Auth.java
  8to10_backend/src/main/java/com/eighttoten/filter/JwtAuthorizationFilter.java
  8to10_backend/src/main/java/com/eighttoten/provider/CustomAuthenticationProvider.java
  8to10_backend/src/main/java/com/eighttoten/repository/auth/AuthRedisRepository.java
  8to10_backend/src/main/java/com/eighttoten/service/auth/AuthService.java
  8to10_backend/src/main/resources/data-dev.sql
  8to10_backend/src/test/java/com/eighttoten/service/auth/AuthServiceTest.java
Labels: enhancement, Refactor

#325 #320[마이페이지 구현]
  8to10_frontend/index.html
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/assets/images/faithfulUser.svg
  8to10_frontend/src/assets/images/normalUser.svg
  8to10_frontend/src/components/PrivateHeader.jsx
  8to10_frontend/src/components/community/post/PostView.jsx
  8to10_frontend/src/components/community/post/reply/CommentItem.jsx
  8to10_frontend/src/components/modal/Modal.jsx
  8to10_frontend/src/components/myPage/ChangeNickname.jsx
  8to10_frontend/src/components/myPage/ChangePassword.jsx
  8to10_frontend/src/components/myPage/ChangeProfileImage.jsx
  8to10_frontend/src/components/myPage/MyBoards.jsx
  8to10_frontend/src/components/myPage/MyPage.jsx
  8to10_frontend/src/components/myPage/MyPageInit.jsx
  8to10_frontend/src/components/myPage/MyReplies.jsx
  8to10_frontend/src/components/myPage/MyScrappedBoards.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/constants/UserRole.js
  8to10_frontend/src/helpers/AxiosHelper.js
  8to10_frontend/src/pages/MyPage.jsx
  8to10_frontend/src/styles/home/LeftSideBar..css
  8to10_frontend/src/styles/modal/Modal.css
  8to10_frontend/src/styles/myPage/MyPage.css
Labels: enhancement

#329 #326[로그아웃 및 회원가입 구현]
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/myPage/ChangeProfileImage.jsx
  8to10_frontend/src/components/myPage/MyPage.jsx
  8to10_frontend/src/components/signUp/SignUp.jsx
  8to10_frontend/src/components/signUp/SignUpComplete.jsx
  8to10_frontend/src/components/signUp/validateSignUp.js
  8to10_frontend/src/components/signUp/validateSignUp.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/constants/ImagePaths.js
  8to10_frontend/src/constants/SignUpValidateMessage.js
  8to10_frontend/src/constants/UserRole.js
  8to10_frontend/src/context/auth/AuthProvider.jsx
  8to10_frontend/src/helpers/AxiosHelper.js
  8to10_frontend/src/helpers/TokenManager.js
  8to10_frontend/src/styles/signUp/SignUp.css
  8to10_frontend/src/styles/signUp/SignUpComplete.css
Labels: enhancement

#332 #331[Dockerfile,Entrypoint 구현]
  8to10_backend/Dockerfile
  8to10_backend/entrypoint.sh
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
Labels: enhancement

#335 deploy-cdn.yml 워크플로우
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#336 #334[README.md 작성]
  README.md
Labels: enhancement

#337 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#338 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#340 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#341 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#342 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#346 #330[일정 수정 구현]/#333-일정-유형별-조회-컴포넌트-분리
  8to10_frontend/package.json
Labels: enhancement

#348 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#350 Update deploy-cdn.yml
  .github/workflows/deploy-cdn.yml
Labels: enhancement

#353 Update README.md
  8to10_frontend/README.md
Labels: enhancement

#356 #330[일정 수정 구현]/#333-일정-유형별-조회-컴포넌트-분리
  8to10_frontend/src/components/home/HomeRightSideBar.jsx
  8to10_frontend/src/components/home/eventDetails/EventDetails.jsx
  8to10_frontend/src/components/home/eventDetails/FScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/NScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/TimeEditForm.jsx
  8to10_frontend/src/components/home/eventDetails/VScheduleDetails.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/home/userStatsCard/UserStatsCard.jsx
  8to10_frontend/src/components/signUp/SignUp.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/helpers/TimeFormatter.js
  8to10_frontend/src/styles/home/RightSideBar.css
Labels: enhancement

#359 #358[README에 ERD 추가]
  README.md
Labels: documentation

#360 Create gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: enhancement

#361 Update gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: enhancement

#362 #331[Dockerfile,Entrypoint 구현]
  8to10_backend/Dockerfile
  8to10_backend/build.gradle
  8to10_backend/entrypoint.sh
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/response/fschedule/FScheduleResponse.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/response/nschedule/NScheduleResponse.java
  8to10_backend/src/main/java/com/eighttoten/repository/board/BoardScrapRepository.java
Labels: enhancement

#364 Update gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: enhancement

#365 Update gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: enhancement

#366 #314[코드 리팩토링]
  8to10_backend/build.gradle
  8to10_backend/src/main/java/com/eighttoten/config/RedisConfig.java
  8to10_backend/src/main/java/com/eighttoten/domain/achievement/Achievement.java
  8to10_backend/src/main/java/com/eighttoten/exception/ExceptionCode.java
  8to10_backend/src/main/java/com/eighttoten/service/achievement/AchievementService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/nschedule/NScheduleDetailService.java
  8to10_backend/src/test/java/com/eighttoten/RedisEmbeddedConfig.java
  8to10_backend/src/test/java/com/eighttoten/TestConfig.java
  8to10_backend/src/test/java/com/eighttoten/repository/MemberRepositoryTest.java
  8to10_backend/src/test/java/com/eighttoten/repository/board/BoardRepositoryCustomImplTest.java
  8to10_backend/src/test/java/com/eighttoten/service/HomeServiceTest.java
Labels: enhancement

#367 Update gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: enhancement

#369 #314[코드 리팩토링]/gitignore-수정
  8to10_backend/.gitignore
  8to10_backend/src/test/resources/application.yaml
Labels: Refactor

#363 변경 사항 배포
  8to10_backend/.gitignore
  8to10_backend/Dockerfile
  8to10_backend/build.gradle
  8to10_backend/entrypoint.sh
  8to10_backend/src/main/java/com/eighttoten/config/RedisConfig.java
  8to10_backend/src/main/java/com/eighttoten/domain/achievement/Achievement.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/response/fschedule/FScheduleResponse.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/response/nschedule/NScheduleResponse.java
  8to10_backend/src/main/java/com/eighttoten/exception/ExceptionCode.java
  8to10_backend/src/main/java/com/eighttoten/repository/board/BoardScrapRepository.java
  8to10_backend/src/main/java/com/eighttoten/service/achievement/AchievementService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/nschedule/NScheduleDetailService.java
  8to10_backend/src/test/java/com/eighttoten/RedisEmbeddedConfig.java
  8to10_backend/src/test/java/com/eighttoten/TestConfig.java
  8to10_backend/src/test/java/com/eighttoten/repository/MemberRepositoryTest.java
  8to10_backend/src/test/java/com/eighttoten/repository/board/BoardRepositoryCustomImplTest.java
  8to10_backend/src/test/java/com/eighttoten/service/HomeServiceTest.java
  8to10_backend/src/test/resources/application.yaml
  8to10_frontend/src/components/home/HomeRightSideBar.jsx
  8to10_frontend/src/components/home/eventDetails/EventDetails.jsx
  8to10_frontend/src/components/home/eventDetails/FScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/NScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/TimeEditForm.jsx
  8to10_frontend/src/components/home/eventDetails/VScheduleDetails.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/home/userStatsCard/UserStatsCard.jsx
  8to10_frontend/src/components/signUp/SignUp.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/helpers/TimeFormatter.js
  8to10_frontend/src/styles/home/RightSideBar.css
  README.md
Labels: enhancement

#382 #314[코드 리팩토링]
  8to10_backend/build.gradle
Labels: Refactor

#383 PR to main
  8to10_backend/build.gradle
Labels: enhancement

#393 Update readme.md
  8to10_backend/docs/readme.md
Labels: documentation

#396 Update gke-deployment.yml
  .github/workflows/gke-deployment.yml
Labels: documentation

#400 #399[URL 변경]
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/vite.config.js
Labels: enhancement

#401 PR to main
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/home/eventDetails/FScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/VScheduleDetails.jsx
  8to10_frontend/src/components/home/todoList/TodoList.jsx
  8to10_frontend/src/components/modal/ConfirmDeleteModal.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/context/auth/AuthProvider.jsx
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/helpers/TimeFormatter.js
  8to10_frontend/src/styles/home/RightSideBar.css
  8to10_frontend/src/styles/modal/ConfirmDeleteModal.css
  8to10_frontend/vite.config.js
Labels: enhancement

#403 Cors설정 변경사항 추가
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
Labels: enhancement

#404 [Feat] URL 수정
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/vite.config.js
Labels: enhancement

#405 URL 변경사항 적용
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/vite.config.js
Labels: enhancement

#407 [BE] Cors 설정 변경
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
Labels: enhancement

#409 #408[healthCheck 컨트롤러 구현]
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/com/eighttoten/controller/HealthCheckController.java
  8to10_backend/src/main/java/com/eighttoten/filter/EmailPasswordAuthenticationFilter.java
  8to10_backend/src/main/java/com/eighttoten/filter/JwtAuthorizationFilter.java
Labels: enhancement

#410 HealthCheck 컨트롤러 반영
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/com/eighttoten/controller/HealthCheckController.java
  8to10_backend/src/main/java/com/eighttoten/filter/EmailPasswordAuthenticationFilter.java
  8to10_backend/src/main/java/com/eighttoten/filter/JwtAuthorizationFilter.java
Labels: enhancement

#412 #411[API 요청 URL 환경변수로 분리]
  8to10_frontend/.gitignore
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/vite.config.js
Labels: enhancement

#414 #413[db 변경]
  8to10_backend/build.gradle
  8to10_backend/src/main/java/com/eighttoten/aspect/ExecutionTimeAspect.java
  8to10_backend/src/main/java/com/eighttoten/config/global/CustomPhysicalNamingStrategy.java
  8to10_backend/src/main/java/com/eighttoten/domain/board/BoardHeart.java
  8to10_backend/src/main/java/com/eighttoten/domain/board/BoardScrap.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FSchedule.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/nschedule/NSchedule.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/nschedule/NScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/vschedule/VSchedule.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/timeslot/TimeSlotService.java
Labels: enhancement

#416 개발 변경사항 반영
  8to10_backend/build.gradle
  8to10_backend/src/main/java/com/eighttoten/aspect/ExecutionTimeAspect.java
  8to10_backend/src/main/java/com/eighttoten/config/global/CustomPhysicalNamingStrategy.java
  8to10_backend/src/main/java/com/eighttoten/domain/board/BoardHeart.java
  8to10_backend/src/main/java/com/eighttoten/domain/board/BoardScrap.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FSchedule.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/fschedule/FScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/nschedule/NSchedule.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/nschedule/NScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/vschedule/VSchedule.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/timeslot/TimeSlotService.java
  8to10_frontend/.gitignore
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/vite.config.js
Labels: enhancement

#418 #417[Sse 객체 타임아웃시 발생하는 Access Denied Exception 해결]
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/response/nschedule/NScheduleResponse.java
  8to10_backend/src/main/java/com/eighttoten/service/notification/SseEmitterService.java
Labels: enhancement

#419 #417[Sse 객체 타임아웃시 발생하는 Access Denied Exception 해결]/로그아웃시 리다이렉트 삭제
  8to10_backend/src/main/java/com/eighttoten/config/auth/SecurityConfig.java
  README.md
Labels: enhancement

#422 #421[TODO를 통한 성취도 업데이트 로직 수정]
  8to10_backend/docs/readme.md
  8to10_backend/src/main/java/com/eighttoten/controller/schedule/NScheduleController.java
  8to10_backend/src/main/java/com/eighttoten/domain/schedule/nschedule/NScheduleDetail.java
  8to10_backend/src/main/java/com/eighttoten/dto/schedule/request/nschedule/ProgressUpdateRequest.java
  8to10_backend/src/main/java/com/eighttoten/exception/ExceptionCode.java
  8to10_backend/src/main/java/com/eighttoten/repository/schedule/nschedule/NScheduleDetailRepository.java
  8to10_backend/src/main/java/com/eighttoten/service/achievement/AchievementService.java
  8to10_backend/src/main/java/com/eighttoten/service/schedule/nschedule/NScheduleDetailService.java
  8to10_backend/src/test/java/com/eighttoten/controller/schedule/NScheduleControllerTest.java
  8to10_backend/src/test/java/com/eighttoten/controller/schedule/VScheduleControllerTest.java
  8to10_backend/src/test/java/com/eighttoten/repository/schedule/ScheduleRepositoryCustomImplTest.java
  8to10_backend/src/test/java/com/eighttoten/service/schedule/nschedule/NScheduleDetailServiceTest.java
  8to10_backend/src/test/java/com/eighttoten/service/schedule/vschedule/VScheduleServiceTest.java
  8to10_backend/src/test/resources/data-test.sql
Labels: enhancement

#427 #426[일반일정 로직수정]
  8to10_backend/src/main/java/com/eighttoten/schedule/domain/repository/ScheduleRepositoryCustomImpl.java
  8to10_backend/src/main/java/com/eighttoten/schedule/service/NScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/schedule/service/ScheduleService.java
  8to10_backend/src/main/java/com/eighttoten/schedule/service/TimeSlotService.java
Labels: enhancement

#428 #314[코드 리팩토링]/Cors Origin 다중 허용
  8to10_backend/src/main/java/com/eighttoten/infrastructure/security/config/SecurityConfig.java
Labels: enhancement

#431 #420[수정사항 구현]
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/PublicApi.js
  8to10_frontend/src/components/PrivateRoute.jsx
  8to10_frontend/src/components/home/FullcalendarView.jsx
  8to10_frontend/src/components/home/HomeRightSideBar.jsx
  8to10_frontend/src/components/home/eventDetails/EventDetails.jsx
  8to10_frontend/src/components/home/eventDetails/FScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/NScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/TimeEditForm.jsx
  8to10_frontend/src/components/home/eventDetails/VScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/ValidateEventDetails.js
  8to10_frontend/src/components/home/todoList/TodoItem.jsx
  8to10_frontend/src/components/home/todoList/TodoItemsList.jsx
  8to10_frontend/src/components/home/todoList/TodoList.jsx
  8to10_frontend/src/components/home/todoList/TodoListHeader.jsx
  8to10_frontend/src/components/home/userStatsCard/UserStatsCard.jsx
  8to10_frontend/src/components/login/Login.jsx
  8to10_frontend/src/components/modal/ConfirmDeleteModal.jsx
  8to10_frontend/src/components/modal/ScheduleDeleteModal.jsx
  8to10_frontend/src/components/notification/Notification.jsx
  8to10_frontend/src/components/notification/NotificationItem.jsx
  8to10_frontend/src/components/notification/NotificationPopup.jsx
  8to10_frontend/src/components/signUp/SignUp.jsx
  8to10_frontend/src/components/signUp/validateSignUp.js
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/constants/ScheduleValidateMessage.js
  8to10_frontend/src/constants/SignUpValidateMessage.js
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/main.jsx
  8to10_frontend/src/styles/home/Fullcalendar.css
  8to10_frontend/src/styles/home/RightSideBar.css
  8to10_frontend/src/styles/home/TodoList.css
  8to10_frontend/src/styles/modal/ConfirmDeleteModal.css
  8to10_frontend/src/styles/modal/ScheduleDeleteModal.css
  8to10_frontend/src/styles/notification/Notification.css
  README.md
Labels: enhancement
