Repository siho-song/8to10, pull requests merged in 2025-04, with the labels that each got.

#451 #446[멀티 모듈화] - 버그 수정
  8to10_backend/8to10_api/build.gradle
  8to10_backend/8to10_api/src/main/java/com/eighttoten/community/PostController.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/community/dto/post/PostPageRequest.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/FScheduleController.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/ScheduleAbleController.java
  8to10_backend/8to10_api/src/test/java/com/eighttoten/schedule/ScheduleAbleControllerTest.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/community/repository/post/PostRepositoryCustomImpl.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/fschedule/repository/FScheduleDetailJpaRepository.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/fschedule/repository/FScheduleDetailRepositoryImpl.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/nschedule/repository/NScheduleDetailJpaRepository.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/nschedule/repository/NScheduleDetailRepositoryImpl.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/vschedule/VScheduleEntity.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/vschedule/repository/VScheduleJpaRepository.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/vschedule/repository/VScheduleRepositoryImpl.java
  8to10_backend/8to10_db/src/test/java/com/eighttoten/schedule/FScheduleDetailRepositoryTest.java
  8to10_backend/8to10_db/src/test/java/com/eighttoten/schedule/NScheduleDetailRepositoryTest.java
  8to10_backend/8to10_db/src/test/java/com/eighttoten/schedule/VScheduleRepositoryTest.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/fschedule/repository/FScheduleDetailRepository.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/nschedule/repository/NScheduleDetailRepository.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/vschedule/repository/VScheduleRepository.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/ScheduleAbleService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/nschedule/NScheduleService.java
  8to10_backend/8to10_domain/src/test/java/com/eighttoten/schedule/service/ScheduleAbleTest.java
  8to10_backend/build.gradle
Labels: bug, enhancement

#452 코드 리팩토링
  8to10_backend/.scannerwork/.sonar_lock
  8to10_backend/.scannerwork/report-task.txt
  8to10_backend/8to10_api/src/main/java/com/eighttoten/community/PostController.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/community/dto/post/PostPageRequest.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/config/WebConfig.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/member/validator/NicknameValidator.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/member/validator/PasswordValidator.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/member/validator/PhoneNumberValidator.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/dto/response/ScheduleResponse.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/validator/fielderror/DayValidator.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/validator/fielderror/FrequencyValidator.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/support/GlobalControllerAdvice.java
  8to10_backend/8to10_api/src/test/java/com/eighttoten/community/PostControllerTest.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/community/repository/post/PostRepositoryCustomImpl.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/common/AppConstant.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/common/Pagination.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/community/event/post/PostStatsUpdateEvent.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/community/event/reply/ReplyStatsUpdateEvent.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/exception/ExceptionCode.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/exception/InternalException.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/exception/InvalidRedisMessageException.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/member/domain/Gender.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/member/domain/Mode.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/member/service/MultipartFileStorageService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/member/service/SignUpService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/domain/FeedbackMessage.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/AsyncNotificationEventHandler.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/RedisMessageSubscriber.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/SseEmitterService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/nschedule/NScheduleCreateInfo.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/nschedule/NScheduleDetailService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/nschedule/NScheduleService.java
  8to10_backend/8to10_security/src/main/java/com/eighttoten/config/SecurityConfig.java
  8to10_backend/8to10_security/src/main/java/com/eighttoten/handler/AuthFilterExceptionHandler.java
  8to10_backend/sonar-project.properties
Labels: Refactor

#454 #453[API 엔드포인트 변경으로 인한 요청 URL 수정]
  8to10_frontend/src/App.jsx
  8to10_frontend/src/api/AuthenticatedApi.js
  8to10_frontend/src/components/PrivateHeader.jsx
  8to10_frontend/src/components/community/board/Board.jsx
  8to10_frontend/src/components/community/board/BoardHeader.jsx
  8to10_frontend/src/components/community/board/BoardList.jsx
  8to10_frontend/src/components/community/board/Pagination.jsx
  8to10_frontend/src/components/community/board/search/PostsPerPage.jsx
  8to10_frontend/src/components/community/post/CreateOrEditPost.jsx
  8to10_frontend/src/components/community/post/PostItem.jsx
  8to10_frontend/src/components/community/post/PostView.jsx
  8to10_frontend/src/components/community/post/reply/CommentItem.jsx
  8to10_frontend/src/components/community/post/reply/CommentSection.jsx
  8to10_frontend/src/components/community/post/reply/CreateComment.jsx
  8to10_frontend/src/components/community/post/reply/ReplyItem.jsx
  8to10_frontend/src/components/home/HomeRightSideBar.jsx
  8to10_frontend/src/components/home/eventDetails/FScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/NScheduleDetails.jsx
  8to10_frontend/src/components/home/eventDetails/VScheduleDetails.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/FixedScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/NormalScheduleForm.jsx
  8to10_frontend/src/components/home/form/ScheduleForm/VariableScheduleForm.jsx
  8to10_frontend/src/components/home/todoList/TodoItem.jsx
  8to10_frontend/src/components/home/todoList/TodoItemsList.jsx
  8to10_frontend/src/components/home/todoList/TodoListHeader.jsx
  8to10_frontend/src/components/myPage/ChangeNickname.jsx
  8to10_frontend/src/components/myPage/DeleteAccount.jsx
  8to10_frontend/src/components/myPage/MyBoards.jsx
  8to10_frontend/src/components/myPage/MyPage.jsx
  8to10_frontend/src/components/myPage/MyReplies.jsx
  8to10_frontend/src/components/myPage/MyScrappedBoards.jsx
  8to10_frontend/src/components/notification/Notification.jsx
  8to10_frontend/src/components/notification/NotificationItem.jsx
  8to10_frontend/src/components/notification/NotificationPopup.jsx
  8to10_frontend/src/constants/ApiEndPoints.js
  8to10_frontend/src/constants/ErrorMessage.js
  8to10_frontend/src/context/fullCalendar/FullCalendarProvider.jsx
  8to10_frontend/src/helpers/AxiosHelper.js
  8to10_frontend/src/helpers/ScheduleFormatter.js
  8to10_frontend/src/helpers/TimeFormatter.js
  8to10_frontend/src/pages/BoardPost.jsx
  8to10_frontend/src/pages/ErrorPage.jsx
  8to10_frontend/src/styles/ErrorPage.css
  8to10_frontend/src/styles/Styles.css
  8to10_frontend/src/styles/community/Board.css
  8to10_frontend/src/styles/home/Fullcalendar.css
  8to10_frontend/src/styles/home/Header.css
  8to10_frontend/src/styles/home/LeftSideBar.css
  8to10_frontend/src/styles/home/RightSideBar.css
  8to10_frontend/src/styles/home/ScheduleForm.css
  8to10_frontend/src/styles/home/ScheduleTypePopup.css
  8to10_frontend/src/styles/home/TodoList.css
  8to10_frontend/src/styles/modal/Modal.css
  8to10_frontend/src/styles/myPage/MyPage.css
  8to10_frontend/src/styles/notification/Notification.css
Labels: enhancement

#455 453 [Feat] API 엔드포인트 변경으로 인한 요청 URL 수정
  8to10_backend/.gitignore
  8to10_backend/.scannerwork/.sonar_lock
  8to10_backend/.scannerwork/report-task.txt
  8to10_backend/8to10_api/Dockerfile
  8to10_backend/8to10_api/build.gradle
  8to10_backend/8to10_api/entrypoint.sh
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/ScheduleAbleController.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/schedule/dto/response/ScheduleResponse.java
  8to10_backend/8to10_api/src/main/java/com/eighttoten/support/HealthCheckController.java
  8to10_backend/8to10_api/src/main/resources/logback.xml
  8to10_backend/8to10_db/build.gradle
  8to10_backend/8to10_db/src/main/java/com/eighttoten/config/RedisConfig.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/notification/NotificationEntity.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/scheduleable/ScheduleAbleRepositoryImpl.java
  8to10_backend/8to10_db/src/main/java/com/eighttoten/schedule/vschedule/VScheduleEntity.java
  8to10_backend/8to10_db/src/test/java/com/eighttoten/notification/NotificationRepositoryTest.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/domain/NewNotification.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/event/NotificationEvent.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/AsyncNotificationEventHandler.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/AsyncNotificationEventPublisher.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/notification/service/RedisMessageSubscriber.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/fschedule/FDetailWithParent.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/fschedule/FScheduleDetail.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/nschedule/NDetailWithParent.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/nschedule/NScheduleDetail.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/scheduleable/ScheduleAble.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/scheduleable/ScheduleAbleRepository.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/scheduleable/ScheduleAbles.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/domain/vschedule/VSchedule.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/ScheduleAbleService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/nschedule/NScheduleService.java
  8to10_backend/8to10_domain/src/main/java/com/eighttoten/schedule/service/nschedule/TimeSlotService.java
  8to10_backend/8to10_domain/src/test/java/com/eighttoten/schedule/service/ScheduleAbleTest.java
  8to10_backend/8to10_domain/src/test/java/com/eighttoten/schedule/service/nschedule/TimeSlotServiceTest.java
  8to10_backend/8to10_scheduling/Dockerfile
  8to10_backend/8to10_scheduling/build.gradle
  8to10_backend/8to10_scheduling/entrypoint.sh
  8to10_backend/8to10_scheduling/src/main/java/com/eighttoten/SchedulingTaskPublisher.java
  8to10_backend/build.gradle
  8to10_backend/gradle.properties
  8to10_backend/sonar-project.properties
Labels: enhancement
